services:
  # onlypandas_api:
  #   build:
  #     context: .
  #     dockerfile: onlypandas.Dockerfile
  #   container_name: onlypandas_api
  #   ports:
  #     - 3033:3000
  #   env_file:
  #     - .env.local
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #
  db:
    image: postgres:14
    container_name: onlypandas_db
    ports:
      - 5423:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:

