services:
  app:
    build:
      context: .
      dockerfile: onlypandas.Dockerfile
    container_name: onlypandas_app
    ports:
      - "3033:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
